# Generated by Django 2.2.6 on 2019-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='departement',
            new_name='department',
        ),
    ]
