# Generated by Django 2.2.6 on 2019-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_backend', '0002_auto_20191105_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='building',
            field=models.TextField(default='ES30i'),
            preserve_default=False,
        ),
    ]
